//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity.Infrastructure.MappingViews;

[assembly: DbMappingViewCacheTypeAttribute(
    typeof(OrdoMill.Data.Model.DbCon),
    typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySets4a5af2831f39838bafa9e4b266b6f76aea27fb4e4c77e60b5ce9042f7e492387))]

namespace Edm_EntityMappingGeneratedViews
{
    using System;
    using System.CodeDom.Compiler;
    using System.Data.Entity.Core.Metadata.Edm;

    /// <summary>
    /// Implements a mapping view cache.
    /// </summary>
    [GeneratedCode("Entity Framework Power Tools", "0.9.0.0")]
    internal sealed class ViewsForBaseEntitySets4a5af2831f39838bafa9e4b266b6f76aea27fb4e4c77e60b5ce9042f7e492387 : DbMappingViewCache
    {
        /// <summary>
        /// Gets a hash value computed over the mapping closure.
        /// </summary>
        public override string MappingHashValue
        {
            get { return "4a5af2831f39838bafa9e4b266b6f76aea27fb4e4c77e60b5ce9042f7e492387"; }
        }

        /// <summary>
        /// Gets a view corresponding to the specified extent.
        /// </summary>
        /// <param name="extent">The extent.</param>
        /// <returns>The mapping view, or null if the extent is not associated with a mapping view.</returns>
        public override DbMappingView GetView(EntitySetBase extent)
        {
            if (extent == null)
            {
                throw new ArgumentNullException("extent");
            }

            var extentName = extent.EntityContainer.Name + "." + extent.Name;

            if (extentName == "CodeFirstDatabase.Assure")
            {
                return GetView0();
            }

            if (extentName == "CodeFirstDatabase.Patient")
            {
                return GetView1();
            }

            if (extentName == "CodeFirstDatabase.Ordonnance")
            {
                return GetView2();
            }

            if (extentName == "CodeFirstDatabase.Facture")
            {
                return GetView3();
            }

            if (extentName == "CodeFirstDatabase.Bordereau")
            {
                return GetView4();
            }

            if (extentName == "CodeFirstDatabase.Medecin")
            {
                return GetView5();
            }

            if (extentName == "CodeFirstDatabase.MedOrd")
            {
                return GetView6();
            }

            if (extentName == "CodeFirstDatabase.Medicament")
            {
                return GetView7();
            }

            if (extentName == "CodeFirstDatabase.Forme")
            {
                return GetView8();
            }

            if (extentName == "CodeFirstDatabase.Historique")
            {
                return GetView9();
            }

            if (extentName == "CodeFirstDatabase.Operation")
            {
                return GetView10();
            }

            if (extentName == "CodeFirstDatabase.User")
            {
                return GetView11();
            }

            if (extentName == "CodeFirstDatabase.Pathologie")
            {
                return GetView12();
            }

            if (extentName == "DbCon.Assures")
            {
                return GetView13();
            }

            if (extentName == "DbCon.Patients")
            {
                return GetView14();
            }

            if (extentName == "DbCon.Ordonnances")
            {
                return GetView15();
            }

            if (extentName == "DbCon.Pathologie_Ordonnances")
            {
                return GetView16();
            }

            if (extentName == "DbCon.Factures")
            {
                return GetView17();
            }

            if (extentName == "DbCon.Bordereaus")
            {
                return GetView18();
            }

            if (extentName == "DbCon.Medecins")
            {
                return GetView19();
            }

            if (extentName == "DbCon.MedOrds")
            {
                return GetView20();
            }

            if (extentName == "DbCon.Medicaments")
            {
                return GetView21();
            }

            if (extentName == "DbCon.Formes")
            {
                return GetView22();
            }

            if (extentName == "DbCon.Historiques")
            {
                return GetView23();
            }

            if (extentName == "DbCon.Operations")
            {
                return GetView24();
            }

            if (extentName == "DbCon.Users")
            {
                return GetView25();
            }

            if (extentName == "DbCon.Pathologies")
            {
                return GetView26();
            }

            if (extentName == "CodeFirstDatabase.Info")
            {
                return GetView27();
            }

            if (extentName == "DbCon.Infos")
            {
                return GetView28();
            }

            return null;
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Assure.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView0()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Assure
        [CodeFirstDatabaseSchema.Assure](T1.Assure_Id, T1.Assure_Matricule, T1.Assure_Nom, T1.Assure_Prenom, T1.Assure_Adresse, T1.Assure_DateNaissance, T1.Assure_Jusquea, T1.Assure_Lieu, T1.Assure_Tel, T1.Assure_Grade, T1.Assure_IsContractial, T1.Assure_Ccp, T1.Assure_ArNom, T1.Assure_ArPrenom, T1.Assure_Note, T1.Assure_Suspende, T1.Assure_FullName, T1.Assure_CreatedAt, T1.Assure_CreatedBy, T1.Assure_ModifiedBy, T1.Assure_ModifiedAt)
    FROM (
        SELECT 
            T.Id AS Assure_Id, 
            T.Matricule AS Assure_Matricule, 
            T.Nom AS Assure_Nom, 
            T.Prenom AS Assure_Prenom, 
            T.Adresse AS Assure_Adresse, 
            T.DateNaissance AS Assure_DateNaissance, 
            T.Jusquea AS Assure_Jusquea, 
            T.Lieu AS Assure_Lieu, 
            T.Tel AS Assure_Tel, 
            T.Grade AS Assure_Grade, 
            T.IsContractial AS Assure_IsContractial, 
            T.Ccp AS Assure_Ccp, 
            T.ArNom AS Assure_ArNom, 
            T.ArPrenom AS Assure_ArPrenom, 
            T.Note AS Assure_Note, 
            T.Suspende AS Assure_Suspende, 
            T.FullName AS Assure_FullName, 
            T.CreatedAt AS Assure_CreatedAt, 
            T.CreatedBy AS Assure_CreatedBy, 
            T.ModifiedBy AS Assure_ModifiedBy, 
            T.ModifiedAt AS Assure_ModifiedAt, 
            True AS _from0
        FROM DbCon.Assures AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Patient.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView1()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Patient
        [CodeFirstDatabaseSchema.Patient](T1.Patient_Id, T1.Patient_Nom, T1.Patient_Prenom, T1.Patient_DateNaissance, T1.Patient_Alliance, T1.Patient_Du, T1.Patient_Au, T1.Patient_AssureId, T1.Patient_Suspende, T1.Patient_CreatedAt, T1.Patient_CreatedBy, T1.Patient_ModifiedBy, T1.Patient_ModifiedAt)
    FROM (
        SELECT 
            T.Id AS Patient_Id, 
            T.Nom AS Patient_Nom, 
            T.Prenom AS Patient_Prenom, 
            T.DateNaissance AS Patient_DateNaissance, 
            T.Alliance AS Patient_Alliance, 
            T.Du AS Patient_Du, 
            T.Au AS Patient_Au, 
            T.AssureId AS Patient_AssureId, 
            T.Suspende AS Patient_Suspende, 
            T.CreatedAt AS Patient_CreatedAt, 
            T.CreatedBy AS Patient_CreatedBy, 
            T.ModifiedBy AS Patient_ModifiedBy, 
            T.ModifiedAt AS Patient_ModifiedAt, 
            True AS _from0
        FROM DbCon.Patients AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Ordonnance.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView2()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Ordonnance
        [CodeFirstDatabaseSchema.Ordonnance](T3.Ordonnance_Id, T3.Ordonnance_ServiDate, T3.Ordonnance_SoineDate, T3.Ordonnance_MedecinId, T3.Ordonnance_PatientId, T3.Ordonnance_FactureId, T3.Ordonnance_IsChronique, T3.Ordonnance_IsHorsRegion, T3.Ordonnance_PathologieCode, T3.Ordonnance_Montant, T3.Ordonnance_CreatedAt, T3.Ordonnance_CreatedBy, T3.Ordonnance_ModifiedBy, T3.Ordonnance_ModifiedAt, T3.[Ordonnance.Pathologie_Id])
    FROM (
        SELECT T1.Ordonnance_Id, T1.Ordonnance_ServiDate, T1.Ordonnance_SoineDate, T1.Ordonnance_MedecinId, T1.Ordonnance_PatientId, T1.Ordonnance_FactureId, T1.Ordonnance_IsChronique, T1.Ordonnance_IsHorsRegion, T1.Ordonnance_PathologieCode, T1.Ordonnance_Montant, T1.Ordonnance_CreatedAt, T1.Ordonnance_CreatedBy, T1.Ordonnance_ModifiedBy, T1.Ordonnance_ModifiedAt, T2.[Ordonnance.Pathologie_Id], T1._from0, (T2._from1 AND T2._from1 IS NOT NULL) AS _from1
        FROM  (
            SELECT 
                T.Id AS Ordonnance_Id, 
                T.ServiDate AS Ordonnance_ServiDate, 
                T.SoineDate AS Ordonnance_SoineDate, 
                T.MedecinId AS Ordonnance_MedecinId, 
                T.PatientId AS Ordonnance_PatientId, 
                T.FactureId AS Ordonnance_FactureId, 
                T.IsChronique AS Ordonnance_IsChronique, 
                T.IsHorsRegion AS Ordonnance_IsHorsRegion, 
                T.PathologieCode AS Ordonnance_PathologieCode, 
                T.Montant AS Ordonnance_Montant, 
                T.CreatedAt AS Ordonnance_CreatedAt, 
                T.CreatedBy AS Ordonnance_CreatedBy, 
                T.ModifiedBy AS Ordonnance_ModifiedBy, 
                T.ModifiedAt AS Ordonnance_ModifiedAt, 
                True AS _from0
            FROM DbCon.Ordonnances AS T) AS T1
            LEFT OUTER JOIN (
            SELECT 
                Key(T.Pathologie_Ordonnances_Target).Id AS Ordonnance_Id, 
                Key(T.Pathologie_Ordonnances_Source).Id AS [Ordonnance.Pathologie_Id], 
                True AS _from1
            FROM DbCon.Pathologie_Ordonnances AS T) AS T2
            ON T1.Ordonnance_Id = T2.Ordonnance_Id
    ) AS T3");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Facture.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView3()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Facture
        [CodeFirstDatabaseSchema.Facture](T1.Facture_Id, T1.Facture_Number, T1.Facture_Chronic, T1.Facture_Out, T1.Facture_Montant, T1.Facture_BordereauId, T1.Facture_CreatedAt, T1.Facture_CreatedBy, T1.Facture_ModifiedBy, T1.Facture_ModifiedAt)
    FROM (
        SELECT 
            T.Id AS Facture_Id, 
            T.Number AS Facture_Number, 
            T.Chronic AS Facture_Chronic, 
            T.Out AS Facture_Out, 
            T.Montant AS Facture_Montant, 
            T.BordereauId AS Facture_BordereauId, 
            T.CreatedAt AS Facture_CreatedAt, 
            T.CreatedBy AS Facture_CreatedBy, 
            T.ModifiedBy AS Facture_ModifiedBy, 
            T.ModifiedAt AS Facture_ModifiedAt, 
            True AS _from0
        FROM DbCon.Factures AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Bordereau.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView4()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Bordereau
        [CodeFirstDatabaseSchema.Bordereau](T1.Bordereau_Id, T1.Bordereau_Date, T1.Bordereau_Number, T1.Bordereau_IsFinished, T1.Bordereau_CreatedAt, T1.Bordereau_CreatedBy, T1.Bordereau_ModifiedBy, T1.Bordereau_ModifiedAt)
    FROM (
        SELECT 
            T.Id AS Bordereau_Id, 
            T.Date AS Bordereau_Date, 
            T.Number AS Bordereau_Number, 
            T.IsFinished AS Bordereau_IsFinished, 
            T.CreatedAt AS Bordereau_CreatedAt, 
            T.CreatedBy AS Bordereau_CreatedBy, 
            T.ModifiedBy AS Bordereau_ModifiedBy, 
            T.ModifiedAt AS Bordereau_ModifiedAt, 
            True AS _from0
        FROM DbCon.Bordereaus AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Medecin.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView5()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Medecin
        [CodeFirstDatabaseSchema.Medecin](T1.Medecin_Id, T1.Medecin_Nom, T1.Medecin_Type, T1.Medecin_Tel, T1.Medecin_Adresse, T1.Medecin_CreatedAt, T1.Medecin_CreatedBy, T1.Medecin_ModifiedBy, T1.Medecin_ModifiedAt)
    FROM (
        SELECT 
            T.Id AS Medecin_Id, 
            T.Nom AS Medecin_Nom, 
            T.Type AS Medecin_Type, 
            T.Tel AS Medecin_Tel, 
            T.Adresse AS Medecin_Adresse, 
            T.CreatedAt AS Medecin_CreatedAt, 
            T.CreatedBy AS Medecin_CreatedBy, 
            T.ModifiedBy AS Medecin_ModifiedBy, 
            T.ModifiedAt AS Medecin_ModifiedAt, 
            True AS _from0
        FROM DbCon.Medecins AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.MedOrd.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView6()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing MedOrd
        [CodeFirstDatabaseSchema.MedOrd](T1.MedOrd_Id, T1.MedOrd_OrdonnanceId, T1.MedOrd_MedicamentId, T1.MedOrd_Duree, T1.MedOrd_Quantite, T1.MedOrd_Ppa, T1.MedOrd_CreatedAt, T1.MedOrd_CreatedBy, T1.MedOrd_ModifiedBy, T1.MedOrd_ModifiedAt)
    FROM (
        SELECT 
            T.Id AS MedOrd_Id, 
            T.OrdonnanceId AS MedOrd_OrdonnanceId, 
            T.MedicamentId AS MedOrd_MedicamentId, 
            T.Duree AS MedOrd_Duree, 
            T.Quantite AS MedOrd_Quantite, 
            T.Ppa AS MedOrd_Ppa, 
            T.CreatedAt AS MedOrd_CreatedAt, 
            T.CreatedBy AS MedOrd_CreatedBy, 
            T.ModifiedBy AS MedOrd_ModifiedBy, 
            T.ModifiedAt AS MedOrd_ModifiedAt, 
            True AS _from0
        FROM DbCon.MedOrds AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Medicament.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView7()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Medicament
        [CodeFirstDatabaseSchema.Medicament](T1.Medicament_Id, T1.Medicament_CnasId, T1.Medicament_Nom, T1.Medicament_Dci, T1.Medicament_Dose, T1.Medicament_Boite, T1.Medicament_Tr, T1.Medicament_Unite, T1.Medicament_Remboursable, T1.Medicament_Controle, T1.Medicament_FormeId, T1.Medicament_CreatedAt, T1.Medicament_CreatedBy, T1.Medicament_ModifiedBy, T1.Medicament_ModifiedAt)
    FROM (
        SELECT 
            T.Id AS Medicament_Id, 
            T.CnasId AS Medicament_CnasId, 
            T.Nom AS Medicament_Nom, 
            T.Dci AS Medicament_Dci, 
            T.Dose AS Medicament_Dose, 
            T.Boite AS Medicament_Boite, 
            T.Tr AS Medicament_Tr, 
            T.Unite AS Medicament_Unite, 
            T.Remboursable AS Medicament_Remboursable, 
            T.Controle AS Medicament_Controle, 
            T.FormeId AS Medicament_FormeId, 
            T.CreatedAt AS Medicament_CreatedAt, 
            T.CreatedBy AS Medicament_CreatedBy, 
            T.ModifiedBy AS Medicament_ModifiedBy, 
            T.ModifiedAt AS Medicament_ModifiedAt, 
            True AS _from0
        FROM DbCon.Medicaments AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Forme.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView8()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Forme
        [CodeFirstDatabaseSchema.Forme](T1.Forme_Id, T1.Forme_Name, T1.Forme_Abrg, T1.Forme_CreatedAt, T1.Forme_CreatedBy, T1.Forme_ModifiedBy, T1.Forme_ModifiedAt)
    FROM (
        SELECT 
            T.Id AS Forme_Id, 
            T.Name AS Forme_Name, 
            T.Abrg AS Forme_Abrg, 
            T.CreatedAt AS Forme_CreatedAt, 
            T.CreatedBy AS Forme_CreatedBy, 
            T.ModifiedBy AS Forme_ModifiedBy, 
            T.ModifiedAt AS Forme_ModifiedAt, 
            True AS _from0
        FROM DbCon.Formes AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Historique.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView9()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Historique
        [CodeFirstDatabaseSchema.Historique](T1.Historique_Id, T1.Historique_PatientId, T1.Historique_DateTime, T1.Historique_Note, T1.Historique_OperationId, T1.Historique_UserId, T1.Historique_CreatedAt, T1.Historique_CreatedBy, T1.Historique_ModifiedBy, T1.Historique_ModifiedAt)
    FROM (
        SELECT 
            T.Id AS Historique_Id, 
            T.PatientId AS Historique_PatientId, 
            T.DateTime AS Historique_DateTime, 
            T.Note AS Historique_Note, 
            T.OperationId AS Historique_OperationId, 
            T.UserId AS Historique_UserId, 
            T.CreatedAt AS Historique_CreatedAt, 
            T.CreatedBy AS Historique_CreatedBy, 
            T.ModifiedBy AS Historique_ModifiedBy, 
            T.ModifiedAt AS Historique_ModifiedAt, 
            True AS _from0
        FROM DbCon.Historiques AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Operation.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView10()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Operation
        [CodeFirstDatabaseSchema.Operation](T1.Operation_Id, T1.Operation_Name, T1.Operation_CreatedAt, T1.Operation_CreatedBy, T1.Operation_ModifiedBy, T1.Operation_ModifiedAt)
    FROM (
        SELECT 
            T.Id AS Operation_Id, 
            T.Name AS Operation_Name, 
            T.CreatedAt AS Operation_CreatedAt, 
            T.CreatedBy AS Operation_CreatedBy, 
            T.ModifiedBy AS Operation_ModifiedBy, 
            T.ModifiedAt AS Operation_ModifiedAt, 
            True AS _from0
        FROM DbCon.Operations AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.User.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView11()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing User
        [CodeFirstDatabaseSchema.User](T1.User_Id, T1.User_UserName, T1.User_Password, T1.User_FullName, T1.User_IsAdmin, T1.User_IsWork, T1.User_AllowAdd, T1.User_AllowUpdate, T1.User_AllowPrintDocs, T1.User_CreatedAt, T1.User_CreatedBy, T1.User_ModifiedBy, T1.User_ModifiedAt)
    FROM (
        SELECT 
            T.Id AS User_Id, 
            T.UserName AS User_UserName, 
            T.Password AS User_Password, 
            T.FullName AS User_FullName, 
            T.IsAdmin AS User_IsAdmin, 
            T.IsWork AS User_IsWork, 
            T.AllowAdd AS User_AllowAdd, 
            T.AllowUpdate AS User_AllowUpdate, 
            T.AllowPrintDocs AS User_AllowPrintDocs, 
            T.CreatedAt AS User_CreatedAt, 
            T.CreatedBy AS User_CreatedBy, 
            T.ModifiedBy AS User_ModifiedBy, 
            T.ModifiedAt AS User_ModifiedAt, 
            True AS _from0
        FROM DbCon.Users AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Pathologie.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView12()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Pathologie
        [CodeFirstDatabaseSchema.Pathologie](T1.Pathologie_Id, T1.Pathologie_Code, T1.Pathologie_Nom, T1.Pathologie_CreatedAt, T1.Pathologie_CreatedBy, T1.Pathologie_ModifiedBy, T1.Pathologie_ModifiedAt)
    FROM (
        SELECT 
            T.Id AS Pathologie_Id, 
            T.Code AS Pathologie_Code, 
            T.Nom AS Pathologie_Nom, 
            T.CreatedAt AS Pathologie_CreatedAt, 
            T.CreatedBy AS Pathologie_CreatedBy, 
            T.ModifiedBy AS Pathologie_ModifiedBy, 
            T.ModifiedAt AS Pathologie_ModifiedAt, 
            True AS _from0
        FROM DbCon.Pathologies AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for DbCon.Assures.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView13()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Assures
        [OrdoMill.Data.Model.Assure](T1.Assure_Id, T1.Assure_Matricule, T1.Assure_Nom, T1.Assure_Prenom, T1.Assure_Adresse, T1.Assure_DateNaissance, T1.Assure_Jusquea, T1.Assure_Lieu, T1.Assure_Tel, T1.Assure_Grade, T1.Assure_IsContractial, T1.Assure_Ccp, T1.Assure_ArNom, T1.Assure_ArPrenom, T1.Assure_Note, T1.Assure_Suspende, T1.Assure_FullName, T1.Assure_CreatedAt, T1.Assure_CreatedBy, T1.Assure_ModifiedBy, T1.Assure_ModifiedAt)
    FROM (
        SELECT 
            T.Id AS Assure_Id, 
            T.Matricule AS Assure_Matricule, 
            T.Nom AS Assure_Nom, 
            T.Prenom AS Assure_Prenom, 
            T.Adresse AS Assure_Adresse, 
            T.DateNaissance AS Assure_DateNaissance, 
            T.Jusquea AS Assure_Jusquea, 
            T.Lieu AS Assure_Lieu, 
            T.Tel AS Assure_Tel, 
            T.Grade AS Assure_Grade, 
            T.IsContractial AS Assure_IsContractial, 
            T.Ccp AS Assure_Ccp, 
            T.ArNom AS Assure_ArNom, 
            T.ArPrenom AS Assure_ArPrenom, 
            T.Note AS Assure_Note, 
            T.Suspende AS Assure_Suspende, 
            T.FullName AS Assure_FullName, 
            T.CreatedAt AS Assure_CreatedAt, 
            T.CreatedBy AS Assure_CreatedBy, 
            T.ModifiedBy AS Assure_ModifiedBy, 
            T.ModifiedAt AS Assure_ModifiedAt, 
            True AS _from0
        FROM CodeFirstDatabase.Assure AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for DbCon.Patients.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView14()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Patients
        [OrdoMill.Data.Model.Patient](T1.Patient_Id, T1.Patient_Nom, T1.Patient_Prenom, T1.Patient_DateNaissance, T1.Patient_Alliance, T1.Patient_Du, T1.Patient_Au, T1.Patient_AssureId, T1.Patient_Suspende, T1.Patient_CreatedAt, T1.Patient_CreatedBy, T1.Patient_ModifiedBy, T1.Patient_ModifiedAt)
    FROM (
        SELECT 
            T.Id AS Patient_Id, 
            T.Nom AS Patient_Nom, 
            T.Prenom AS Patient_Prenom, 
            T.DateNaissance AS Patient_DateNaissance, 
            T.Alliance AS Patient_Alliance, 
            T.Du AS Patient_Du, 
            T.Au AS Patient_Au, 
            T.AssureId AS Patient_AssureId, 
            T.Suspende AS Patient_Suspende, 
            T.CreatedAt AS Patient_CreatedAt, 
            T.CreatedBy AS Patient_CreatedBy, 
            T.ModifiedBy AS Patient_ModifiedBy, 
            T.ModifiedAt AS Patient_ModifiedAt, 
            True AS _from0
        FROM CodeFirstDatabase.Patient AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for DbCon.Ordonnances.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView15()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Ordonnances
        [OrdoMill.Data.Model.Ordonnance](T1.Ordonnance_Id, T1.Ordonnance_ServiDate, T1.Ordonnance_SoineDate, T1.Ordonnance_MedecinId, T1.Ordonnance_PatientId, T1.Ordonnance_FactureId, T1.Ordonnance_IsChronique, T1.Ordonnance_IsHorsRegion, T1.Ordonnance_PathologieCode, T1.Ordonnance_Montant, T1.Ordonnance_CreatedAt, T1.Ordonnance_CreatedBy, T1.Ordonnance_ModifiedBy, T1.Ordonnance_ModifiedAt) WITH 
        RELATIONSHIP(CREATEREF(DbCon.Pathologies, ROW(T1.[Pathologie_Ordonnances.Pathologie_Ordonnances_Source.Id]),[OrdoMill.Data.Model.Pathologie]),[OrdoMill.Data.Model.Pathologie_Ordonnances],Pathologie_Ordonnances_Target,Pathologie_Ordonnances_Source) 
    FROM (
        SELECT 
            T.Id AS Ordonnance_Id, 
            T.ServiDate AS Ordonnance_ServiDate, 
            T.SoineDate AS Ordonnance_SoineDate, 
            T.MedecinId AS Ordonnance_MedecinId, 
            T.PatientId AS Ordonnance_PatientId, 
            T.FactureId AS Ordonnance_FactureId, 
            T.IsChronique AS Ordonnance_IsChronique, 
            T.IsHorsRegion AS Ordonnance_IsHorsRegion, 
            T.PathologieCode AS Ordonnance_PathologieCode, 
            T.Montant AS Ordonnance_Montant, 
            T.CreatedAt AS Ordonnance_CreatedAt, 
            T.CreatedBy AS Ordonnance_CreatedBy, 
            T.ModifiedBy AS Ordonnance_ModifiedBy, 
            T.ModifiedAt AS Ordonnance_ModifiedAt, 
            True AS _from0, 
            T.Pathologie_Id AS [Pathologie_Ordonnances.Pathologie_Ordonnances_Source.Id]
        FROM CodeFirstDatabase.Ordonnance AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for DbCon.Pathologie_Ordonnances.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView16()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Pathologie_Ordonnances
        [OrdoMill.Data.Model.Pathologie_Ordonnances](T3.[Pathologie_Ordonnances.Pathologie_Ordonnances_Source], T3.[Pathologie_Ordonnances.Pathologie_Ordonnances_Target])
    FROM (
        SELECT -- Constructing Pathologie_Ordonnances_Source
            CreateRef(DbCon.Pathologies, row(T2.[Pathologie_Ordonnances.Pathologie_Ordonnances_Source.Id]), [OrdoMill.Data.Model.Pathologie]) AS [Pathologie_Ordonnances.Pathologie_Ordonnances_Source], 
            T2.[Pathologie_Ordonnances.Pathologie_Ordonnances_Target]
        FROM (
            SELECT -- Constructing Pathologie_Ordonnances_Target
                T1.[Pathologie_Ordonnances.Pathologie_Ordonnances_Source.Id], 
                CreateRef(DbCon.Ordonnances, row(T1.[Pathologie_Ordonnances.Pathologie_Ordonnances_Target.Id]), [OrdoMill.Data.Model.Ordonnance]) AS [Pathologie_Ordonnances.Pathologie_Ordonnances_Target]
            FROM (
                SELECT 
                    T.Pathologie_Id AS [Pathologie_Ordonnances.Pathologie_Ordonnances_Source.Id], 
                    T.Id AS [Pathologie_Ordonnances.Pathologie_Ordonnances_Target.Id], 
                    True AS _from0
                FROM CodeFirstDatabase.Ordonnance AS T
                WHERE T.Pathologie_Id IS NOT NULL
            ) AS T1
        ) AS T2
    ) AS T3");
        }

        /// <summary>
        /// Gets the view for DbCon.Factures.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView17()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Factures
        [OrdoMill.Data.Model.Facture](T1.Facture_Id, T1.Facture_Number, T1.Facture_Chronic, T1.Facture_Out, T1.Facture_Montant, T1.Facture_BordereauId, T1.Facture_CreatedAt, T1.Facture_CreatedBy, T1.Facture_ModifiedBy, T1.Facture_ModifiedAt)
    FROM (
        SELECT 
            T.Id AS Facture_Id, 
            T.Number AS Facture_Number, 
            T.Chronic AS Facture_Chronic, 
            T.Out AS Facture_Out, 
            T.Montant AS Facture_Montant, 
            T.BordereauId AS Facture_BordereauId, 
            T.CreatedAt AS Facture_CreatedAt, 
            T.CreatedBy AS Facture_CreatedBy, 
            T.ModifiedBy AS Facture_ModifiedBy, 
            T.ModifiedAt AS Facture_ModifiedAt, 
            True AS _from0
        FROM CodeFirstDatabase.Facture AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for DbCon.Bordereaus.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView18()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Bordereaus
        [OrdoMill.Data.Model.Bordereau](T1.Bordereau_Id, T1.Bordereau_Date, T1.Bordereau_Number, T1.Bordereau_IsFinished, T1.Bordereau_CreatedAt, T1.Bordereau_CreatedBy, T1.Bordereau_ModifiedBy, T1.Bordereau_ModifiedAt)
    FROM (
        SELECT 
            T.Id AS Bordereau_Id, 
            T.Date AS Bordereau_Date, 
            T.Number AS Bordereau_Number, 
            T.IsFinished AS Bordereau_IsFinished, 
            T.CreatedAt AS Bordereau_CreatedAt, 
            T.CreatedBy AS Bordereau_CreatedBy, 
            T.ModifiedBy AS Bordereau_ModifiedBy, 
            T.ModifiedAt AS Bordereau_ModifiedAt, 
            True AS _from0
        FROM CodeFirstDatabase.Bordereau AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for DbCon.Medecins.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView19()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Medecins
        [OrdoMill.Data.Model.Medecin](T1.Medecin_Id, T1.Medecin_Nom, T1.Medecin_Type, T1.Medecin_Tel, T1.Medecin_Adresse, T1.Medecin_CreatedAt, T1.Medecin_CreatedBy, T1.Medecin_ModifiedBy, T1.Medecin_ModifiedAt)
    FROM (
        SELECT 
            T.Id AS Medecin_Id, 
            T.Nom AS Medecin_Nom, 
            T.Type AS Medecin_Type, 
            T.Tel AS Medecin_Tel, 
            T.Adresse AS Medecin_Adresse, 
            T.CreatedAt AS Medecin_CreatedAt, 
            T.CreatedBy AS Medecin_CreatedBy, 
            T.ModifiedBy AS Medecin_ModifiedBy, 
            T.ModifiedAt AS Medecin_ModifiedAt, 
            True AS _from0
        FROM CodeFirstDatabase.Medecin AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for DbCon.MedOrds.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView20()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing MedOrds
        [OrdoMill.Data.Model.MedOrd](T1.MedOrd_Id, T1.MedOrd_OrdonnanceId, T1.MedOrd_MedicamentId, T1.MedOrd_Duree, T1.MedOrd_Quantite, T1.MedOrd_Ppa, T1.MedOrd_CreatedAt, T1.MedOrd_CreatedBy, T1.MedOrd_ModifiedBy, T1.MedOrd_ModifiedAt)
    FROM (
        SELECT 
            T.Id AS MedOrd_Id, 
            T.OrdonnanceId AS MedOrd_OrdonnanceId, 
            T.MedicamentId AS MedOrd_MedicamentId, 
            T.Duree AS MedOrd_Duree, 
            T.Quantite AS MedOrd_Quantite, 
            T.Ppa AS MedOrd_Ppa, 
            T.CreatedAt AS MedOrd_CreatedAt, 
            T.CreatedBy AS MedOrd_CreatedBy, 
            T.ModifiedBy AS MedOrd_ModifiedBy, 
            T.ModifiedAt AS MedOrd_ModifiedAt, 
            True AS _from0
        FROM CodeFirstDatabase.MedOrd AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for DbCon.Medicaments.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView21()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Medicaments
        [OrdoMill.Data.Model.Medicament](T1.Medicament_Id, T1.Medicament_CnasId, T1.Medicament_Nom, T1.Medicament_Dci, T1.Medicament_Dose, T1.Medicament_Boite, T1.Medicament_Tr, T1.Medicament_Unite, T1.Medicament_Remboursable, T1.Medicament_Controle, T1.Medicament_FormeId, T1.Medicament_CreatedAt, T1.Medicament_CreatedBy, T1.Medicament_ModifiedBy, T1.Medicament_ModifiedAt)
    FROM (
        SELECT 
            T.Id AS Medicament_Id, 
            T.CnasId AS Medicament_CnasId, 
            T.Nom AS Medicament_Nom, 
            T.Dci AS Medicament_Dci, 
            T.Dose AS Medicament_Dose, 
            T.Boite AS Medicament_Boite, 
            T.Tr AS Medicament_Tr, 
            T.Unite AS Medicament_Unite, 
            T.Remboursable AS Medicament_Remboursable, 
            T.Controle AS Medicament_Controle, 
            T.FormeId AS Medicament_FormeId, 
            T.CreatedAt AS Medicament_CreatedAt, 
            T.CreatedBy AS Medicament_CreatedBy, 
            T.ModifiedBy AS Medicament_ModifiedBy, 
            T.ModifiedAt AS Medicament_ModifiedAt, 
            True AS _from0
        FROM CodeFirstDatabase.Medicament AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for DbCon.Formes.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView22()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Formes
        [OrdoMill.Data.Model.Forme](T1.Forme_Id, T1.Forme_Name, T1.Forme_Abrg, T1.Forme_CreatedAt, T1.Forme_CreatedBy, T1.Forme_ModifiedBy, T1.Forme_ModifiedAt)
    FROM (
        SELECT 
            T.Id AS Forme_Id, 
            T.Name AS Forme_Name, 
            T.Abrg AS Forme_Abrg, 
            T.CreatedAt AS Forme_CreatedAt, 
            T.CreatedBy AS Forme_CreatedBy, 
            T.ModifiedBy AS Forme_ModifiedBy, 
            T.ModifiedAt AS Forme_ModifiedAt, 
            True AS _from0
        FROM CodeFirstDatabase.Forme AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for DbCon.Historiques.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView23()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Historiques
        [OrdoMill.Data.Model.Historique](T1.Historique_Id, T1.Historique_PatientId, T1.Historique_DateTime, T1.Historique_Note, T1.Historique_OperationId, T1.Historique_UserId, T1.Historique_CreatedAt, T1.Historique_CreatedBy, T1.Historique_ModifiedBy, T1.Historique_ModifiedAt)
    FROM (
        SELECT 
            T.Id AS Historique_Id, 
            T.PatientId AS Historique_PatientId, 
            T.DateTime AS Historique_DateTime, 
            T.Note AS Historique_Note, 
            T.OperationId AS Historique_OperationId, 
            T.UserId AS Historique_UserId, 
            T.CreatedAt AS Historique_CreatedAt, 
            T.CreatedBy AS Historique_CreatedBy, 
            T.ModifiedBy AS Historique_ModifiedBy, 
            T.ModifiedAt AS Historique_ModifiedAt, 
            True AS _from0
        FROM CodeFirstDatabase.Historique AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for DbCon.Operations.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView24()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Operations
        [OrdoMill.Data.Model.Operation](T1.Operation_Id, T1.Operation_Name, T1.Operation_CreatedAt, T1.Operation_CreatedBy, T1.Operation_ModifiedBy, T1.Operation_ModifiedAt)
    FROM (
        SELECT 
            T.Id AS Operation_Id, 
            T.Name AS Operation_Name, 
            T.CreatedAt AS Operation_CreatedAt, 
            T.CreatedBy AS Operation_CreatedBy, 
            T.ModifiedBy AS Operation_ModifiedBy, 
            T.ModifiedAt AS Operation_ModifiedAt, 
            True AS _from0
        FROM CodeFirstDatabase.Operation AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for DbCon.Users.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView25()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Users
        [OrdoMill.Data.Model.User](T1.User_Id, T1.User_UserName, T1.User_Password, T1.User_FullName, T1.User_IsAdmin, T1.User_IsWork, T1.User_AllowAdd, T1.User_AllowUpdate, T1.User_AllowPrintDocs, T1.User_CreatedAt, T1.User_CreatedBy, T1.User_ModifiedBy, T1.User_ModifiedAt)
    FROM (
        SELECT 
            T.Id AS User_Id, 
            T.UserName AS User_UserName, 
            T.Password AS User_Password, 
            T.FullName AS User_FullName, 
            T.IsAdmin AS User_IsAdmin, 
            T.IsWork AS User_IsWork, 
            T.AllowAdd AS User_AllowAdd, 
            T.AllowUpdate AS User_AllowUpdate, 
            T.AllowPrintDocs AS User_AllowPrintDocs, 
            T.CreatedAt AS User_CreatedAt, 
            T.CreatedBy AS User_CreatedBy, 
            T.ModifiedBy AS User_ModifiedBy, 
            T.ModifiedAt AS User_ModifiedAt, 
            True AS _from0
        FROM CodeFirstDatabase.User AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for DbCon.Pathologies.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView26()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Pathologies
        [OrdoMill.Data.Model.Pathologie](T1.Pathologie_Id, T1.Pathologie_Code, T1.Pathologie_Nom, T1.Pathologie_CreatedAt, T1.Pathologie_CreatedBy, T1.Pathologie_ModifiedBy, T1.Pathologie_ModifiedAt)
    FROM (
        SELECT 
            T.Id AS Pathologie_Id, 
            T.Code AS Pathologie_Code, 
            T.Nom AS Pathologie_Nom, 
            T.CreatedAt AS Pathologie_CreatedAt, 
            T.CreatedBy AS Pathologie_CreatedBy, 
            T.ModifiedBy AS Pathologie_ModifiedBy, 
            T.ModifiedAt AS Pathologie_ModifiedAt, 
            True AS _from0
        FROM CodeFirstDatabase.Pathologie AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Info.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView27()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Info
        [CodeFirstDatabaseSchema.Info](T1.Info_Id, T1.Info_Pharmacie, T1.Info_Adresse, T1.Info_Tel, T1.Info_Fax, T1.Info_CodeFiscal, T1.Info_Article, T1.Info_Rc, T1.Info_Ccp, T1.Info_Doit, T1.Info_Code, T1.Info_Region, T1.Info_CreatedAt, T1.Info_CreatedBy, T1.Info_ModifiedBy, T1.Info_ModifiedAt)
    FROM (
        SELECT 
            T.Id AS Info_Id, 
            T.Pharmacie AS Info_Pharmacie, 
            T.Adresse AS Info_Adresse, 
            T.Tel AS Info_Tel, 
            T.Fax AS Info_Fax, 
            T.CodeFiscal AS Info_CodeFiscal, 
            T.Article AS Info_Article, 
            T.Rc AS Info_Rc, 
            T.Ccp AS Info_Ccp, 
            T.Doit AS Info_Doit, 
            T.Code AS Info_Code, 
            T.Region AS Info_Region, 
            T.CreatedAt AS Info_CreatedAt, 
            T.CreatedBy AS Info_CreatedBy, 
            T.ModifiedBy AS Info_ModifiedBy, 
            T.ModifiedAt AS Info_ModifiedAt, 
            True AS _from0
        FROM DbCon.Infos AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for DbCon.Infos.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView28()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Infos
        [OrdoMill.Data.Model.Info](T1.Info_Id, T1.Info_Pharmacie, T1.Info_Adresse, T1.Info_Tel, T1.Info_Fax, T1.Info_CodeFiscal, T1.Info_Article, T1.Info_Rc, T1.Info_Ccp, T1.Info_Doit, T1.Info_Code, T1.Info_Region, T1.Info_CreatedAt, T1.Info_CreatedBy, T1.Info_ModifiedBy, T1.Info_ModifiedAt)
    FROM (
        SELECT 
            T.Id AS Info_Id, 
            T.Pharmacie AS Info_Pharmacie, 
            T.Adresse AS Info_Adresse, 
            T.Tel AS Info_Tel, 
            T.Fax AS Info_Fax, 
            T.CodeFiscal AS Info_CodeFiscal, 
            T.Article AS Info_Article, 
            T.Rc AS Info_Rc, 
            T.Ccp AS Info_Ccp, 
            T.Doit AS Info_Doit, 
            T.Code AS Info_Code, 
            T.Region AS Info_Region, 
            T.CreatedAt AS Info_CreatedAt, 
            T.CreatedBy AS Info_CreatedBy, 
            T.ModifiedBy AS Info_ModifiedBy, 
            T.ModifiedAt AS Info_ModifiedAt, 
            True AS _from0
        FROM CodeFirstDatabase.Info AS T
    ) AS T1");
        }
    }
}
