//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdoMill.GlobalResources.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrdoMill.GlobalResources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] E1 {
            get {
                object obj = ResourceManager.GetObject("E1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001AEROSOL                                          AERO.               
        ///002AMPOULE                                          AMP.                
        ///003AMPOULE BUVABLE                                  AMP.BUV.            
        ///004AMPOULE INJECTABLE                               AMP.INJ.            
        ///005BOITE                                            BTE.                
        ///007CAPSULE                                          CAPS.               
        ///008CAPSULE SPINHALER                                CAPS.+SPINA      [rest of string was truncated]&quot;;.
        /// </summary>
        public static byte[] FORME {
            get {
                object obj = ResourceManager.GetString("FORME", resourceCulture);
                return ((byte[])(obj));

            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00010ZYRTEC                                            CETIRIZINE                                        10MG                          MG                  B/10                 O10061997                       6000   143   O 04601A0039713032010 G                    10En cas de prescription de ce medicament antérieure à la date du 13.03.2010, il y&apos;a lieu d&apos;appliquer le tarif de référence suivant: 75.00DA.                                                                                                            [rest of string was truncated]&quot;;.
        /// </summary>
        public static byte[] MEDIC {
            get {
                object obj = ResourceManager.GetString("MEDIC", resourceCulture);
                return ((byte[])(obj));

            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0001,Stérilité
        ///0100,Tuberculose sous toutes ses formes
        ///0200,Les pseycho-nevroses graves
        ///0300,Les maladies cancéreuses
        ///0400,Les hélopathies
        ///0500,Les sarcoidoses
        ///0600,L&apos;hypertension artérielle maligne
        ///0700,Les maladies cardiaques et vasculaires acquises et congénitales
        ///0701,Angine de poitrine
        ///0702,Infractus du myocarde
        ///0703,Pontage Aorto-Coronarien
        ///0704,Remplacement Valvulaire prothetique
        ///0705,Valvulopathies
        ///0706,Maladies athero mateuses évoluées
        ///0707,Arterite des membres inferieurs
        ///0708,Accide [rest of string was truncated]&quot;;.
        /// </summary>
        public static byte[] PathologiesU {
            get {
                object obj = ResourceManager.GetObject("PathologiesU", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] R1 {
            get {
                object obj = ResourceManager.GetObject("R1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] T1 {
            get {
                object obj = ResourceManager.GetObject("T1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] T2 {
            get {
                object obj = ResourceManager.GetObject("T2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] T3 {
            get {
                object obj = ResourceManager.GetObject("T3", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
