

//// ------------------------------------------------------------------------------------------------
//// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
//// Created by Simon Hughes (https://about.me/simon.hughes).
////
//// Do not make changes directly to this file - edit the template instead.
////
//// The following connection settings were used to generate this file:
////     Configuration file:     "OrdoMill\App.config"
////     Connection String Name: "DbCon"
////     Connection String:      "Data Source=.\SQLExpress;Initial Catalog=OrdoMill_Db;Integrated Security=True;MultipleActiveResultSets=True"
//// ------------------------------------------------------------------------------------------------
//// Database Edition       : Express Edition (64-bit)
//// Database Engine Edition: Express

//// <auto-generated>
//// ReSharper disable ConvertPropertyToExpressionBody
//// ReSharper disable DoNotCallOverridableMethodsInConstructor
//// ReSharper disable InconsistentNaming
//// ReSharper disable PartialMethodWithSinglePart
//// ReSharper disable PartialTypeWithSinglePart
//// ReSharper disable RedundantNameQualifier
//// ReSharper disable RedundantOverridenMember
//// ReSharper disable UseNameofExpression
//// TargetFrameworkVersion = 4.5
//#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


//namespace OrdoMill.Dto
//{
//    using System.Linq;

//    #region Unit of work

//    public interface IMyDbCon : System.IDisposable
//    {
//        System.Data.Entity.DbSet<Assure> Assures { get; set; } // Assures
//        System.Data.Entity.DbSet<Bordereau> Bordereaux { get; set; } // Bordereaux
//        System.Data.Entity.DbSet<Facture> Factures { get; set; } // Factures
//        System.Data.Entity.DbSet<Forme> Formes { get; set; } // Formes
//        System.Data.Entity.DbSet<Historique> Historiques { get; set; } // Historiques
//        System.Data.Entity.DbSet<Info> Infoes { get; set; } // Infoes
//        System.Data.Entity.DbSet<Medecin> Medecins { get; set; } // Medecins
//        System.Data.Entity.DbSet<Medicament> Medicaments { get; set; } // Medicaments
//        System.Data.Entity.DbSet<MedOrd> MedOrds { get; set; } // MedOrds
//        System.Data.Entity.DbSet<Operation> Operations { get; set; } // Operations
//        System.Data.Entity.DbSet<Ordonnance> Ordonnances { get; set; } // Ordonnances
//        System.Data.Entity.DbSet<Pathology> Pathologies { get; set; } // Pathologies
//        System.Data.Entity.DbSet<Patient> Patients { get; set; } // Patients
//        System.Data.Entity.DbSet<User> Users { get; set; } // Users

//        int SaveChanges();
//        System.Threading.Tasks.Task<int> SaveChangesAsync();
//        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
//        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
//        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
//        System.Data.Entity.Database Database { get; }
//        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
//        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
//        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
//        System.Data.Entity.DbSet Set(System.Type entityType);
//        System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
//        string ToString();
//    }

//    #endregion

//    #region Database context

//    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
//    public class MyDbCon : System.Data.Entity.DbContext, IMyDbCon
//    {
//        public System.Data.Entity.DbSet<Assure> Assures { get; set; } // Assures
//        public System.Data.Entity.DbSet<Bordereau> Bordereaux { get; set; } // Bordereaux
//        public System.Data.Entity.DbSet<Facture> Factures { get; set; } // Factures
//        public System.Data.Entity.DbSet<Forme> Formes { get; set; } // Formes
//        public System.Data.Entity.DbSet<Historique> Historiques { get; set; } // Historiques
//        public System.Data.Entity.DbSet<Info> Infoes { get; set; } // Infoes
//        public System.Data.Entity.DbSet<Medecin> Medecins { get; set; } // Medecins
//        public System.Data.Entity.DbSet<Medicament> Medicaments { get; set; } // Medicaments
//        public System.Data.Entity.DbSet<MedOrd> MedOrds { get; set; } // MedOrds
//        public System.Data.Entity.DbSet<Operation> Operations { get; set; } // Operations
//        public System.Data.Entity.DbSet<Ordonnance> Ordonnances { get; set; } // Ordonnances
//        public System.Data.Entity.DbSet<Pathology> Pathologies { get; set; } // Pathologies
//        public System.Data.Entity.DbSet<Patient> Patients { get; set; } // Patients
//        public System.Data.Entity.DbSet<User> Users { get; set; } // Users

//        static MyDbCon()
//        {
//            System.Data.Entity.Database.SetInitializer<MyDbCon>(null);
//        }

//        public MyDbCon()
//            : base("Name=DbCon")
//        {
//        }

//        public MyDbCon(string connectionString)
//            : base(connectionString)
//        {
//        }

//        public MyDbCon(string connectionString, System.Data.Entity.Infrastructure.DbCompiledModel model)
//            : base(connectionString, model)
//        {
//        }

//        public MyDbCon(System.Data.Common.DbConnection existingConnection, bool contextOwnsConnection)
//            : base(existingConnection, contextOwnsConnection)
//        {
//        }

//        public MyDbCon(System.Data.Common.DbConnection existingConnection, System.Data.Entity.Infrastructure.DbCompiledModel model, bool contextOwnsConnection)
//            : base(existingConnection, model, contextOwnsConnection)
//        {
//        }

//        protected override void Dispose(bool disposing)
//        {
//            base.Dispose(disposing);
//        }

//        public bool IsSqlParameterNull(System.Data.SqlClient.SqlParameter param)
//        {
//            var sqlValue = param.SqlValue;
//            var nullableValue = sqlValue as System.Data.SqlTypes.INullable;
//            if (nullableValue != null)
//                return nullableValue.IsNull;
//            return (sqlValue == null || sqlValue == System.DBNull.Value);
//        }

//        protected override void OnModelCreating(System.Data.Entity.DbModelBuilder modelBuilder)
//        {
//            base.OnModelCreating(modelBuilder);

//            modelBuilder.Configurations.Add(new AssureConfiguration());
//            modelBuilder.Configurations.Add(new BordereauConfiguration());
//            modelBuilder.Configurations.Add(new FactureConfiguration());
//            modelBuilder.Configurations.Add(new FormeConfiguration());
//            modelBuilder.Configurations.Add(new HistoriqueConfiguration());
//            modelBuilder.Configurations.Add(new InfoConfiguration());
//            modelBuilder.Configurations.Add(new MedecinConfiguration());
//            modelBuilder.Configurations.Add(new MedicamentConfiguration());
//            modelBuilder.Configurations.Add(new MedOrdConfiguration());
//            modelBuilder.Configurations.Add(new OperationConfiguration());
//            modelBuilder.Configurations.Add(new OrdonnanceConfiguration());
//            modelBuilder.Configurations.Add(new PathologyConfiguration());
//            modelBuilder.Configurations.Add(new PatientConfiguration());
//            modelBuilder.Configurations.Add(new UserConfiguration());
//        }

//        public static System.Data.Entity.DbModelBuilder CreateModel(System.Data.Entity.DbModelBuilder modelBuilder, string schema)
//        {
//            modelBuilder.Configurations.Add(new AssureConfiguration(schema));
//            modelBuilder.Configurations.Add(new BordereauConfiguration(schema));
//            modelBuilder.Configurations.Add(new FactureConfiguration(schema));
//            modelBuilder.Configurations.Add(new FormeConfiguration(schema));
//            modelBuilder.Configurations.Add(new HistoriqueConfiguration(schema));
//            modelBuilder.Configurations.Add(new InfoConfiguration(schema));
//            modelBuilder.Configurations.Add(new MedecinConfiguration(schema));
//            modelBuilder.Configurations.Add(new MedicamentConfiguration(schema));
//            modelBuilder.Configurations.Add(new MedOrdConfiguration(schema));
//            modelBuilder.Configurations.Add(new OperationConfiguration(schema));
//            modelBuilder.Configurations.Add(new OrdonnanceConfiguration(schema));
//            modelBuilder.Configurations.Add(new PathologyConfiguration(schema));
//            modelBuilder.Configurations.Add(new PatientConfiguration(schema));
//            modelBuilder.Configurations.Add(new UserConfiguration(schema));
//            return modelBuilder;
//        }
//    }
//    #endregion

//    #region Fake Database context

//    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
//    public class FakeMyDbCon : IMyDbCon
//    {
//        public System.Data.Entity.DbSet<Assure> Assures { get; set; }
//        public System.Data.Entity.DbSet<Bordereau> Bordereaux { get; set; }
//        public System.Data.Entity.DbSet<Facture> Factures { get; set; }
//        public System.Data.Entity.DbSet<Forme> Formes { get; set; }
//        public System.Data.Entity.DbSet<Historique> Historiques { get; set; }
//        public System.Data.Entity.DbSet<Info> Infoes { get; set; }
//        public System.Data.Entity.DbSet<Medecin> Medecins { get; set; }
//        public System.Data.Entity.DbSet<Medicament> Medicaments { get; set; }
//        public System.Data.Entity.DbSet<MedOrd> MedOrds { get; set; }
//        public System.Data.Entity.DbSet<Operation> Operations { get; set; }
//        public System.Data.Entity.DbSet<Ordonnance> Ordonnances { get; set; }
//        public System.Data.Entity.DbSet<Pathology> Pathologies { get; set; }
//        public System.Data.Entity.DbSet<Patient> Patients { get; set; }
//        public System.Data.Entity.DbSet<User> Users { get; set; }

//        public FakeMyDbCon()
//        {
//            Assures = new FakeDbSet<Assure>("Id");
//            Bordereaux = new FakeDbSet<Bordereau>("Id");
//            Factures = new FakeDbSet<Facture>("Id");
//            Formes = new FakeDbSet<Forme>("Id");
//            Historiques = new FakeDbSet<Historique>("Id");
//            Infoes = new FakeDbSet<Info>("Id");
//            Medecins = new FakeDbSet<Medecin>("Id");
//            Medicaments = new FakeDbSet<Medicament>("Id");
//            MedOrds = new FakeDbSet<MedOrd>("Id");
//            Operations = new FakeDbSet<Operation>("Id");
//            Ordonnances = new FakeDbSet<Ordonnance>("Id");
//            Pathologies = new FakeDbSet<Pathology>("Id");
//            Patients = new FakeDbSet<Patient>("Id");
//            Users = new FakeDbSet<User>("Id");
//        }

//        public int SaveChangesCount { get; private set; }
//        public int SaveChanges()
//        {
//            ++SaveChangesCount;
//            return 1;
//        }

//        public System.Threading.Tasks.Task<int> SaveChangesAsync()
//        {
//            ++SaveChangesCount;
//            return System.Threading.Tasks.Task<int>.Factory.StartNew(() => 1);
//        }

//        public System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken)
//        {
//            ++SaveChangesCount;
//            return System.Threading.Tasks.Task<int>.Factory.StartNew(() => 1, cancellationToken);
//        }

//        protected virtual void Dispose(bool disposing)
//        {
//        }

//        public void Dispose()
//        {
//            Dispose(true);
//        }

//        public System.Data.Entity.Infrastructure.DbChangeTracker _changeTracker;
//        public System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get { return _changeTracker; } }
//        public System.Data.Entity.Infrastructure.DbContextConfiguration _configuration;
//        public System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get { return _configuration; } }
//        public System.Data.Entity.Database _database;
//        public System.Data.Entity.Database Database { get { return _database; } }
//        public System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class
//        {
//            throw new System.NotImplementedException();
//        }
//        public System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity)
//        {
//            throw new System.NotImplementedException();
//        }
//        public System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors()
//        {
//            throw new System.NotImplementedException();
//        }
//        public System.Data.Entity.DbSet Set(System.Type entityType)
//        {
//            throw new System.NotImplementedException();
//        }
//        public System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class
//        {
//            throw new System.NotImplementedException();
//        }
//        public override string ToString()
//        {
//            throw new System.NotImplementedException();
//        }

//    }

//    // ************************************************************************
//    // Fake DbSet
//    // Implementing Find:
//    //      The Find method is difficult to implement in a generic fashion. If
//    //      you need to test code that makes use of the Find method it is
//    //      easiest to create a test DbSet for each of the entity types that
//    //      need to support find. You can then write logic to find that
//    //      particular type of entity, as shown below:
//    //      public class FakeBlogDbSet : FakeDbSet<Blog>
//    //      {
//    //          public override Blog Find(params object[] keyValues)
//    //          {
//    //              var id = (int) keyValues.Single();
//    //              return this.SingleOrDefault(b => b.BlogId == id);
//    //          }
//    //      }
//    //      Read more about it here: https://msdn.microsoft.com/en-us/data/dn314431.aspx
//    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
//    public class FakeDbSet<TEntity> : System.Data.Entity.DbSet<TEntity>, IQueryable, System.Collections.Generic.IEnumerable<TEntity>, System.Data.Entity.Infrastructure.IDbAsyncEnumerable<TEntity> where TEntity : class
//    {
//        private readonly System.Reflection.PropertyInfo[] _primaryKeys;
//        private readonly System.Collections.ObjectModel.ObservableCollection<TEntity> _data;
//        private readonly IQueryable _query;

//        public FakeDbSet()
//        {
//            _data = new System.Collections.ObjectModel.ObservableCollection<TEntity>();
//            _query = _data.AsQueryable();
//        }

//        public FakeDbSet(params string[] primaryKeys)
//        {
//            _primaryKeys = typeof(TEntity).GetProperties().Where(x => primaryKeys.Contains(x.Name)).ToArray();
//            _data = new System.Collections.ObjectModel.ObservableCollection<TEntity>();
//            _query = _data.AsQueryable();
//        }

//        public override TEntity Find(params object[] keyValues)
//        {
//            if (_primaryKeys == null)
//                throw new System.ArgumentException("No primary keys defined");
//            if (keyValues.Length != _primaryKeys.Length)
//                throw new System.ArgumentException("Incorrect number of keys passed to Find method");

//            var keyQuery = this.AsQueryable();
//            keyQuery = keyValues
//                .Select((t, i) => i)
//                .Aggregate(keyQuery,
//                    (current, x) =>
//                        current.Where(entity => _primaryKeys[x].GetValue(entity, null).Equals(keyValues[x])));

//            return keyQuery.SingleOrDefault();
//        }

//        public override System.Threading.Tasks.Task<TEntity> FindAsync(System.Threading.CancellationToken cancellationToken, params object[] keyValues)
//        {
//            return System.Threading.Tasks.Task<TEntity>.Factory.StartNew(() => Find(keyValues), cancellationToken);
//        }

//        public override System.Threading.Tasks.Task<TEntity> FindAsync(params object[] keyValues)
//        {
//            return System.Threading.Tasks.Task<TEntity>.Factory.StartNew(() => Find(keyValues));
//        }

//        public override System.Collections.Generic.IEnumerable<TEntity> AddRange(System.Collections.Generic.IEnumerable<TEntity> entities)
//        {
//            if (entities == null) throw new System.ArgumentNullException("entities");
//            var items = entities.ToList();
//            foreach (var entity in items)
//            {
//                _data.Add(entity);
//            }
//            return items;
//        }

//        public override TEntity Add(TEntity item)
//        {
//            if (item == null) throw new System.ArgumentNullException("item");
//            _data.Add(item);
//            return item;
//        }

//        public override System.Collections.Generic.IEnumerable<TEntity> RemoveRange(System.Collections.Generic.IEnumerable<TEntity> entities)
//        {
//            if (entities == null) throw new System.ArgumentNullException("entities");
//            var items = entities.ToList();
//            foreach (var entity in items)
//            {
//                _data.Remove(entity);
//            }
//            return items;
//        }

//        public override TEntity Remove(TEntity item)
//        {
//            if (item == null) throw new System.ArgumentNullException("item");
//            _data.Remove(item);
//            return item;
//        }

//        public override TEntity Attach(TEntity item)
//        {
//            if (item == null) throw new System.ArgumentNullException("item");
//            _data.Add(item);
//            return item;
//        }

//        public override TEntity Create()
//        {
//            return System.Activator.CreateInstance<TEntity>();
//        }

//        public override TDerivedEntity Create<TDerivedEntity>()
//        {
//            return System.Activator.CreateInstance<TDerivedEntity>();
//        }

//        public override System.Collections.ObjectModel.ObservableCollection<TEntity> Local
//        {
//            get { return _data; }
//        }

//        System.Type IQueryable.ElementType
//        {
//            get { return _query.ElementType; }
//        }

//        System.Linq.Expressions.Expression IQueryable.Expression
//        {
//            get { return _query.Expression; }
//        }

//        IQueryProvider IQueryable.Provider
//        {
//            get { return new FakeDbAsyncQueryProvider<TEntity>(_query.Provider); }
//        }

//        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
//        {
//            return _data.GetEnumerator();
//        }

//        System.Collections.Generic.IEnumerator<TEntity> System.Collections.Generic.IEnumerable<TEntity>.GetEnumerator()
//        {
//            return _data.GetEnumerator();
//        }

//        System.Data.Entity.Infrastructure.IDbAsyncEnumerator<TEntity> System.Data.Entity.Infrastructure.IDbAsyncEnumerable<TEntity>.GetAsyncEnumerator()
//        {
//            return new FakeDbAsyncEnumerator<TEntity>(_data.GetEnumerator());
//        }
//    }

//    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
//    public class FakeDbAsyncQueryProvider<TEntity> : System.Data.Entity.Infrastructure.IDbAsyncQueryProvider
//    {
//        private readonly IQueryProvider _inner;

//        public FakeDbAsyncQueryProvider(IQueryProvider inner)
//        {
//            _inner = inner;
//        }

//        public IQueryable CreateQuery(System.Linq.Expressions.Expression expression)
//        {
//            return new FakeDbAsyncEnumerable<TEntity>(expression);
//        }

//        public IQueryable<TElement> CreateQuery<TElement>(System.Linq.Expressions.Expression expression)
//        {
//            return new FakeDbAsyncEnumerable<TElement>(expression);
//        }

//        public object Execute(System.Linq.Expressions.Expression expression)
//        {
//            return _inner.Execute(expression);
//        }

//        public TResult Execute<TResult>(System.Linq.Expressions.Expression expression)
//        {
//            return _inner.Execute<TResult>(expression);
//        }

//        public System.Threading.Tasks.Task<object> ExecuteAsync(System.Linq.Expressions.Expression expression, System.Threading.CancellationToken cancellationToken)
//        {
//            return System.Threading.Tasks.Task.FromResult(Execute(expression));
//        }

//        public System.Threading.Tasks.Task<TResult> ExecuteAsync<TResult>(System.Linq.Expressions.Expression expression, System.Threading.CancellationToken cancellationToken)
//        {
//            return System.Threading.Tasks.Task.FromResult(Execute<TResult>(expression));
//        }
//    }

//    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
//    public class FakeDbAsyncEnumerable<T> : EnumerableQuery<T>, System.Data.Entity.Infrastructure.IDbAsyncEnumerable<T>, IQueryable<T>
//    {
//        public FakeDbAsyncEnumerable(System.Collections.Generic.IEnumerable<T> enumerable)
//            : base(enumerable)
//        { }

//        public FakeDbAsyncEnumerable(System.Linq.Expressions.Expression expression)
//            : base(expression)
//        { }

//        public System.Data.Entity.Infrastructure.IDbAsyncEnumerator<T> GetAsyncEnumerator()
//        {
//            return new FakeDbAsyncEnumerator<T>(this.AsEnumerable().GetEnumerator());
//        }

//        System.Data.Entity.Infrastructure.IDbAsyncEnumerator System.Data.Entity.Infrastructure.IDbAsyncEnumerable.GetAsyncEnumerator()
//        {
//            return GetAsyncEnumerator();
//        }

//        IQueryProvider IQueryable.Provider
//        {
//            get { return new FakeDbAsyncQueryProvider<T>(this); }
//        }
//    }

//    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
//    public class FakeDbAsyncEnumerator<T> : System.Data.Entity.Infrastructure.IDbAsyncEnumerator<T>
//    {
//        private readonly System.Collections.Generic.IEnumerator<T> _inner;

//        public FakeDbAsyncEnumerator(System.Collections.Generic.IEnumerator<T> inner)
//        {
//            _inner = inner;
//        }

//        public void Dispose()
//        {
//            _inner.Dispose();
//        }

//        public System.Threading.Tasks.Task<bool> MoveNextAsync(System.Threading.CancellationToken cancellationToken)
//        {
//            return System.Threading.Tasks.Task.FromResult(_inner.MoveNext());
//        }

//        public T Current
//        {
//            get { return _inner.Current; }
//        }

//        object System.Data.Entity.Infrastructure.IDbAsyncEnumerator.Current
//        {
//            get { return Current; }
//        }
//    }

//    #endregion

//    //#region POCO classes

//    //// Assures
//    //[System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
//    //public class Assure
//    //{
//    //    public int Id { get; set; } // Id (Primary key)
//    //    public string Matricule { get; set; } // Matricule
//    //    public string Nom { get; set; } // Nom
//    //    public string Prenom { get; set; } // Prenom
//    //    public string Adresse { get; set; } // Adresse
//    //    public System.DateTime? DateNaissance { get; set; } // DateNaissance
//    //    public System.DateTime? Jusquea { get; set; } // Jusquea
//    //    public string Lieu { get; set; } // Lieu
//    //    public string Tel { get; set; } // Tel
//    //    public string Grade { get; set; } // Grade
//    //    public bool IsContractial { get; set; } // IsContractial
//    //    public string Ccp { get; set; } // Ccp
//    //    public string ArNom { get; set; } // ArNom
//    //    public string ArPrenom { get; set; } // ArPrenom
//    //    public string Note { get; set; } // Note
//    //    public bool Suspende { get; set; } // Suspende
//    //    public System.DateTime? CreatedAt { get; set; } // CreatedAt
//    //    public string CreatedBy { get; set; } // CreatedBy
//    //    public string ModifiedBy { get; set; } // ModifiedBy
//    //    public System.DateTime? ModifiedAt { get; set; } // ModifiedAt
//    //    public string FullName { get; set; } // FullName

//    //    // Reverse navigation
//    //    public virtual System.Collections.Generic.ICollection<Patient> Patients { get; set; } // Patients.FK_dbo.Patients_dbo.Assures_AssureId

//    //    public Assure()
//    //    {
//    //        Patients = new System.Collections.Generic.List<Patient>();
//    //    }
//    //}

//    //// Bordereaux
//    //[System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
//    //public class Bordereau
//    //{
//    //    public int Id { get; set; } // Id (Primary key)
//    //    public System.DateTime? Date { get; set; } // Date
//    //    public int Number { get; set; } // Number
//    //    public bool IsFinished { get; set; } // IsFinished
//    //    public System.DateTime? CreatedAt { get; set; } // CreatedAt
//    //    public string CreatedBy { get; set; } // CreatedBy
//    //    public string ModifiedBy { get; set; } // ModifiedBy
//    //    public System.DateTime? ModifiedAt { get; set; } // ModifiedAt

//    //    // Reverse navigation
//    //    public virtual System.Collections.Generic.ICollection<Facture> Factures { get; set; } // Factures.FK_dbo.Factures_dbo.Bordereaux_BordereauId

//    //    public Bordereau()
//    //    {
//    //        Factures = new System.Collections.Generic.List<Facture>();
//    //    }
//    //}

//    //// Factures
//    //[System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
//    //public class Facture
//    //{
//    //    public int Id { get; set; } // Id (Primary key)
//    //    public int Number { get; set; } // Number
//    //    public bool Chronic { get; set; } // Chronic
//    //    public bool Out { get; set; } // Out
//    //    public int? BordereauId { get; set; } // BordereauId
//    //    public System.DateTime? CreatedAt { get; set; } // CreatedAt
//    //    public string CreatedBy { get; set; } // CreatedBy
//    //    public string ModifiedBy { get; set; } // ModifiedBy
//    //    public System.DateTime? ModifiedAt { get; set; } // ModifiedAt

//    //    // Reverse navigation
//    //    public virtual System.Collections.Generic.ICollection<Ordonnance> Ordonnances { get; set; } // Ordonnances.FK_dbo.Ordonnances_dbo.Factures_FactureId

//    //    // Foreign keys
//    //    public virtual Bordereau Bordereau { get; set; } // FK_dbo.Factures_dbo.Bordereaux_BordereauId

//    //    public Facture()
//    //    {
//    //        Ordonnances = new System.Collections.Generic.List<Ordonnance>();
//    //    }
//    //}

//    //// Formes
//    //[System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
//    //public class Forme
//    //{
//    //    public int Id { get; set; } // Id (Primary key)
//    //    public string Name { get; set; } // Name
//    //    public string Abrg { get; set; } // Abrg
//    //    public System.DateTime? CreatedAt { get; set; } // CreatedAt
//    //    public string CreatedBy { get; set; } // CreatedBy
//    //    public string ModifiedBy { get; set; } // ModifiedBy
//    //    public System.DateTime? ModifiedAt { get; set; } // ModifiedAt

//    //    // Reverse navigation
//    //    public virtual System.Collections.Generic.ICollection<Medicament> Medicaments { get; set; } // Medicaments.FK_dbo.Medicaments_dbo.Formes_FormeId

//    //    public Forme()
//    //    {
//    //        Medicaments = new System.Collections.Generic.List<Medicament>();
//    //    }
//    //}

//    //// Historiques
//    //[System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
//    //public class Historique
//    //{
//    //    public int Id { get; set; } // Id (Primary key)
//    //    public int? PatientId { get; set; } // PatientId
//    //    public System.DateTime DateTime { get; set; } // DateTime
//    //    public string Note { get; set; } // Note
//    //    public int? OperationId { get; set; } // OperationId
//    //    public int? UserId { get; set; } // UserId
//    //    public System.DateTime? CreatedAt { get; set; } // CreatedAt
//    //    public string CreatedBy { get; set; } // CreatedBy
//    //    public string ModifiedBy { get; set; } // ModifiedBy
//    //    public System.DateTime? ModifiedAt { get; set; } // ModifiedAt

//    //    // Foreign keys
//    //    public virtual Operation Operation { get; set; } // FK_dbo.Historiques_dbo.Operations_OperationId
//    //    public virtual Patient Patient { get; set; } // FK_dbo.Historiques_dbo.Patients_PatientId
//    //    public virtual User User { get; set; } // FK_dbo.Historiques_dbo.Users_UserId
//    //}

//    //// Infoes
//    //[System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
//    //public class Info
//    //{
//    //    public int Id { get; set; } // Id (Primary key)
//    //    public string Pharmacie { get; set; } // Pharmacie
//    //    public string Adresse { get; set; } // Adresse
//    //    public string Tel { get; set; } // Tel
//    //    public string Fax { get; set; } // Fax
//    //    public string CodeFiscal { get; set; } // CodeFiscal
//    //    public string Article { get; set; } // Article
//    //    public string Rc { get; set; } // Rc
//    //    public string Ccp { get; set; } // Ccp
//    //    public string Doit { get; set; } // Doit
//    //    public string Code { get; set; } // Code
//    //    public string Region { get; set; } // Region
//    //    public System.DateTime? CreatedAt { get; set; } // CreatedAt
//    //    public string CreatedBy { get; set; } // CreatedBy
//    //    public string ModifiedBy { get; set; } // ModifiedBy
//    //    public System.DateTime? ModifiedAt { get; set; } // ModifiedAt
//    //}

//    //// Medecins
//    //[System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
//    //public class Medecin
//    //{
//    //    public int Id { get; set; } // Id (Primary key)
//    //    public string Nom { get; set; } // Nom
//    //    public string Tel { get; set; } // Tel
//    //    public string Adresse { get; set; } // Adresse
//    //    public int Type { get; set; } // Type
//    //    public System.DateTime? CreatedAt { get; set; } // CreatedAt
//    //    public string CreatedBy { get; set; } // CreatedBy
//    //    public string ModifiedBy { get; set; } // ModifiedBy
//    //    public System.DateTime? ModifiedAt { get; set; } // ModifiedAt

//    //    // Reverse navigation
//    //    public virtual System.Collections.Generic.ICollection<Ordonnance> Ordonnances { get; set; } // Ordonnances.FK_dbo.Ordonnances_dbo.Medecins_MedecinId

//    //    public Medecin()
//    //    {
//    //        Ordonnances = new System.Collections.Generic.List<Ordonnance>();
//    //    }
//    //}

//    //// Medicaments
//    //[System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
//    //public class Medicament
//    //{
//    //    public int Id { get; set; } // Id (Primary key)
//    //    public string CnasId { get; set; } // CnasId
//    //    public string Nom { get; set; } // Nom
//    //    public string Dci { get; set; } // Dci
//    //    public string Dose { get; set; } // Dose
//    //    public string Boite { get; set; } // Boite
//    //    public string Tr { get; set; } // Tr
//    //    public string Unite { get; set; } // Unite
//    //    public bool Remboursable { get; set; } // Remboursable
//    //    public bool Controle { get; set; } // Controle
//    //    public int? FormeId { get; set; } // FormeId
//    //    public System.DateTime? CreatedAt { get; set; } // CreatedAt
//    //    public string CreatedBy { get; set; } // CreatedBy
//    //    public string ModifiedBy { get; set; } // ModifiedBy
//    //    public System.DateTime? ModifiedAt { get; set; } // ModifiedAt

//    //    // Reverse navigation
//    //    public virtual System.Collections.Generic.ICollection<MedOrd> MedOrds { get; set; } // MedOrds.FK_dbo.MedOrds_dbo.Medicaments_MedicamentId

//    //    // Foreign keys
//    //    public virtual Forme Forme { get; set; } // FK_dbo.Medicaments_dbo.Formes_FormeId

//    //    public Medicament()
//    //    {
//    //        MedOrds = new System.Collections.Generic.List<MedOrd>();
//    //    }
//    //}

//    //// MedOrds
//    //[System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
//    //public class MedOrd
//    //{
//    //    public int Id { get; set; } // Id (Primary key)
//    //    public int OrdonnanceId { get; set; } // OrdonnanceId
//    //    public int MedicamentId { get; set; } // MedicamentId
//    //    public int Duree { get; set; } // Duree
//    //    public int Quantite { get; set; } // Quantite
//    //    public double Ppa { get; set; } // Ppa
//    //    public System.DateTime? CreatedAt { get; set; } // CreatedAt
//    //    public string CreatedBy { get; set; } // CreatedBy
//    //    public string ModifiedBy { get; set; } // ModifiedBy
//    //    public System.DateTime? ModifiedAt { get; set; } // ModifiedAt

//    //    // Foreign keys
//    //    public virtual Medicament Medicament { get; set; } // FK_dbo.MedOrds_dbo.Medicaments_MedicamentId
//    //    public virtual Ordonnance Ordonnance { get; set; } // FK_dbo.MedOrds_dbo.Ordonnances_OrdonnanceId
//    //}

//    //// Operations
//    //[System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
//    //public class Operation
//    //{
//    //    public int Id { get; set; } // Id (Primary key)
//    //    public string Name { get; set; } // Name
//    //    public System.DateTime? CreatedAt { get; set; } // CreatedAt
//    //    public string CreatedBy { get; set; } // CreatedBy
//    //    public string ModifiedBy { get; set; } // ModifiedBy
//    //    public System.DateTime? ModifiedAt { get; set; } // ModifiedAt

//    //    // Reverse navigation
//    //    public virtual System.Collections.Generic.ICollection<Historique> Historiques { get; set; } // Historiques.FK_dbo.Historiques_dbo.Operations_OperationId

//    //    public Operation()
//    //    {
//    //        Historiques = new System.Collections.Generic.List<Historique>();
//    //    }
//    //}

//    //// Ordonnances
//    //[System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
//    //public class Ordonnance
//    //{
//    //    public int Id { get; set; } // Id (Primary key)
//    //    public System.DateTime ServiDate { get; set; } // ServiDate
//    //    public System.DateTime SoineDate { get; set; } // SoineDate
//    //    public int? MedecinId { get; set; } // MedecinId
//    //    public int PatientId { get; set; } // PatientId
//    //    public int? FactureId { get; set; } // FactureId
//    //    public bool IsChronique { get; set; } // IsChronique
//    //    public bool IsHorsRegion { get; set; } // IsHorsRegion
//    //    public string PathologieCode { get; set; } // PathologieCode
//    //    public System.DateTime? CreatedAt { get; set; } // CreatedAt
//    //    public string CreatedBy { get; set; } // CreatedBy
//    //    public string ModifiedBy { get; set; } // ModifiedBy
//    //    public System.DateTime? ModifiedAt { get; set; } // ModifiedAt
//    //    public int? PathologieId { get; set; } // Pathologie_Id

//    //    // Reverse navigation
//    //    public virtual System.Collections.Generic.ICollection<MedOrd> MedOrds { get; set; } // MedOrds.FK_dbo.MedOrds_dbo.Ordonnances_OrdonnanceId

//    //    // Foreign keys
//    //    public virtual Facture Facture { get; set; } // FK_dbo.Ordonnances_dbo.Factures_FactureId
//    //    public virtual Medecin Medecin { get; set; } // FK_dbo.Ordonnances_dbo.Medecins_MedecinId
//    //    public virtual Pathology Pathology { get; set; } // FK_dbo.Ordonnances_dbo.Pathologies_Pathologie_Id
//    //    public virtual Patient Patient { get; set; } // FK_dbo.Ordonnances_dbo.Patients_PatientId

//    //    public Ordonnance()
//    //    {
//    //        MedOrds = new System.Collections.Generic.List<MedOrd>();
//    //    }
//    //}

//    //// Pathologies
//    //[System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
//    //public class Pathology
//    //{
//    //    public int Id { get; set; } // Id (Primary key)
//    //    public string Code { get; set; } // Code
//    //    public string Nom { get; set; } // Nom
//    //    public System.DateTime? CreatedAt { get; set; } // CreatedAt
//    //    public string CreatedBy { get; set; } // CreatedBy
//    //    public string ModifiedBy { get; set; } // ModifiedBy
//    //    public System.DateTime? ModifiedAt { get; set; } // ModifiedAt

//    //    // Reverse navigation
//    //    public virtual System.Collections.Generic.ICollection<Ordonnance> Ordonnances { get; set; } // Ordonnances.FK_dbo.Ordonnances_dbo.Pathologies_Pathologie_Id

//    //    public Pathology()
//    //    {
//    //        Ordonnances = new System.Collections.Generic.List<Ordonnance>();
//    //    }
//    //}

//    //// Patients
//    //[System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
//    //public class Patient
//    //{
//    //    public int Id { get; set; } // Id (Primary key)
//    //    public string Nom { get; set; } // Nom
//    //    public string Prenom { get; set; } // Prenom
//    //    public System.DateTime? DateNaissance { get; set; } // DateNaissance
//    //    public int Alliance { get; set; } // Alliance
//    //    public System.DateTime? Du { get; set; } // Du
//    //    public System.DateTime? Au { get; set; } // Au
//    //    public int AssureId { get; set; } // AssureId
//    //    public bool Suspende { get; set; } // Suspende
//    //    public System.DateTime? CreatedAt { get; set; } // CreatedAt
//    //    public string CreatedBy { get; set; } // CreatedBy
//    //    public string ModifiedBy { get; set; } // ModifiedBy
//    //    public System.DateTime? ModifiedAt { get; set; } // ModifiedAt

//    //    // Reverse navigation
//    //    public virtual System.Collections.Generic.ICollection<Historique> Historiques { get; set; } // Historiques.FK_dbo.Historiques_dbo.Patients_PatientId
//    //    public virtual System.Collections.Generic.ICollection<Ordonnance> Ordonnances { get; set; } // Ordonnances.FK_dbo.Ordonnances_dbo.Patients_PatientId

//    //    // Foreign keys
//    //    public virtual Assure Assure { get; set; } // FK_dbo.Patients_dbo.Assures_AssureId

//    //    public Patient()
//    //    {
//    //        Historiques = new System.Collections.Generic.List<Historique>();
//    //        Ordonnances = new System.Collections.Generic.List<Ordonnance>();
//    //    }
//    //}

//    //// Users
//    //[System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
//    //public class User
//    //{
//    //    public int Id { get; set; } // Id (Primary key)
//    //    public string UserName { get; set; } // UserName
//    //    public string Password { get; set; } // Password
//    //    public string FullName { get; set; } // FullName
//    //    public bool IsAdmin { get; set; } // IsAdmin
//    //    public bool IsWork { get; set; } // IsWork
//    //    public bool AllowAdd { get; set; } // AllowAdd
//    //    public bool AllowUpdate { get; set; } // AllowUpdate
//    //    public bool AllowPrintDocs { get; set; } // AllowPrintDocs
//    //    public System.DateTime? CreatedAt { get; set; } // CreatedAt
//    //    public string CreatedBy { get; set; } // CreatedBy
//    //    public string ModifiedBy { get; set; } // ModifiedBy
//    //    public System.DateTime? ModifiedAt { get; set; } // ModifiedAt

//    //    // Reverse navigation
//    //    public virtual System.Collections.Generic.ICollection<Historique> Historiques { get; set; } // Historiques.FK_dbo.Historiques_dbo.Users_UserId

//    //    public User()
//    //    {
//    //        Historiques = new System.Collections.Generic.List<Historique>();
//    //    }
//    //}

//    //#endregion

//    #region POCO Configuration

//    // Assures
//    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
//    public class AssureConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Assure>
//    {
//        public AssureConfiguration()
//            : this("dbo")
//        {
//        }

//        public AssureConfiguration(string schema)
//        {
//            ToTable("Assures", schema);
//            HasKey(x => x.Id);

//            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
//            Property(x => x.Matricule).HasColumnName(@"Matricule").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.Nom).HasColumnName(@"Nom").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.Prenom).HasColumnName(@"Prenom").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.Adresse).HasColumnName(@"Adresse").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.DateNaissance).HasColumnName(@"DateNaissance").HasColumnType("datetime").IsOptional();
//            Property(x => x.Jusquea).HasColumnName(@"Jusquea").HasColumnType("datetime").IsOptional();
//            Property(x => x.Lieu).HasColumnName(@"Lieu").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.Tel).HasColumnName(@"Tel").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.Grade).HasColumnName(@"Grade").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.IsContractial).HasColumnName(@"IsContractial").HasColumnType("bit").IsRequired();
//            Property(x => x.Ccp).HasColumnName(@"Ccp").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.ArNom).HasColumnName(@"ArNom").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.ArPrenom).HasColumnName(@"ArPrenom").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.Note).HasColumnName(@"Note").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.Suspende).HasColumnName(@"Suspende").HasColumnType("bit").IsRequired();
//            Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").HasColumnType("datetime").IsOptional();
//            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.ModifiedAt).HasColumnName(@"ModifiedAt").HasColumnType("datetime").IsOptional();
//            Property(x => x.FullName).HasColumnName(@"FullName").HasColumnType("nvarchar(max)").IsOptional();
//        }
//    }

//    // Bordereaux
//    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
//    public class BordereauConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Bordereau>
//    {
//        public BordereauConfiguration()
//            : this("dbo")
//        {
//        }

//        public BordereauConfiguration(string schema)
//        {
//            ToTable("Bordereaux", schema);
//            HasKey(x => x.Id);

//            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
//            Property(x => x.Date).HasColumnName(@"Date").HasColumnType("datetime").IsOptional();
//            Property(x => x.Number).HasColumnName(@"Number").HasColumnType("int").IsRequired();
//            Property(x => x.IsFinished).HasColumnName(@"IsFinished").HasColumnType("bit").IsRequired();
//            Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").HasColumnType("datetime").IsOptional();
//            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.ModifiedAt).HasColumnName(@"ModifiedAt").HasColumnType("datetime").IsOptional();
//        }
//    }

//    // Factures
//    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
//    public class FactureConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Facture>
//    {
//        public FactureConfiguration()
//            : this("dbo")
//        {
//        }

//        public FactureConfiguration(string schema)
//        {
//            ToTable("Factures", schema);
//            HasKey(x => x.Id);

//            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
//            Property(x => x.Number).HasColumnName(@"Number").HasColumnType("int").IsRequired();
//            Property(x => x.Chronic).HasColumnName(@"Chronic").HasColumnType("bit").IsRequired();
//            Property(x => x.Out).HasColumnName(@"Out").HasColumnType("bit").IsRequired();
//            Property(x => x.BordereauId).HasColumnName(@"BordereauId").HasColumnType("int").IsOptional();
//            Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").HasColumnType("datetime").IsOptional();
//            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.ModifiedAt).HasColumnName(@"ModifiedAt").HasColumnType("datetime").IsOptional();

//            // Foreign keys
//            HasOptional(a => a.Bordereau).WithMany(b => b.Factures).HasForeignKey(c => c.BordereauId).WillCascadeOnDelete(false); // FK_dbo.Factures_dbo.Bordereaux_BordereauId
//        }
//    }

//    // Formes
//    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
//    public class FormeConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Forme>
//    {
//        public FormeConfiguration()
//            : this("dbo")
//        {
//        }

//        public FormeConfiguration(string schema)
//        {
//            ToTable("Formes", schema);
//            HasKey(x => x.Id);

//            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
//            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.Abrg).HasColumnName(@"Abrg").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").HasColumnType("datetime").IsOptional();
//            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.ModifiedAt).HasColumnName(@"ModifiedAt").HasColumnType("datetime").IsOptional();
//        }
//    }

//    // Historiques
//    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
//    public class HistoriqueConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Historique>
//    {
//        public HistoriqueConfiguration()
//            : this("dbo")
//        {
//        }

//        public HistoriqueConfiguration(string schema)
//        {
//            ToTable("Historiques", schema);
//            HasKey(x => x.Id);

//            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
//            Property(x => x.PatientId).HasColumnName(@"PatientId").HasColumnType("int").IsOptional();
//            Property(x => x.DateTime).HasColumnName(@"DateTime").HasColumnType("datetime").IsRequired();
//            Property(x => x.Note).HasColumnName(@"Note").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.OperationId).HasColumnName(@"OperationId").HasColumnType("int").IsOptional();
//            Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("int").IsOptional();
//            Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").HasColumnType("datetime").IsOptional();
//            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.ModifiedAt).HasColumnName(@"ModifiedAt").HasColumnType("datetime").IsOptional();

//            // Foreign keys
//            HasOptional(a => a.Operation).WithMany(b => b.Historiques).HasForeignKey(c => c.OperationId).WillCascadeOnDelete(false); // FK_dbo.Historiques_dbo.Operations_OperationId
//            HasOptional(a => a.Patient).WithMany(b => b.Historiques).HasForeignKey(c => c.PatientId).WillCascadeOnDelete(false); // FK_dbo.Historiques_dbo.Patients_PatientId
//            HasOptional(a => a.User).WithMany(b => b.Historiques).HasForeignKey(c => c.UserId).WillCascadeOnDelete(false); // FK_dbo.Historiques_dbo.Users_UserId
//        }
//    }

//    // Infoes
//    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
//    public class InfoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Info>
//    {
//        public InfoConfiguration()
//            : this("dbo")
//        {
//        }

//        public InfoConfiguration(string schema)
//        {
//            ToTable("Infoes", schema);
//            HasKey(x => x.Id);

//            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
//            Property(x => x.Pharmacie).HasColumnName(@"Pharmacie").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.Adresse).HasColumnName(@"Adresse").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.Tel).HasColumnName(@"Tel").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.Fax).HasColumnName(@"Fax").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.CodeFiscal).HasColumnName(@"CodeFiscal").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.Article).HasColumnName(@"Article").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.Rc).HasColumnName(@"Rc").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.Ccp).HasColumnName(@"Ccp").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.Doit).HasColumnName(@"Doit").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.Code).HasColumnName(@"Code").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.Region).HasColumnName(@"Region").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").HasColumnType("datetime").IsOptional();
//            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.ModifiedAt).HasColumnName(@"ModifiedAt").HasColumnType("datetime").IsOptional();
//        }
//    }

//    // Medecins
//    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
//    public class MedecinConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Medecin>
//    {
//        public MedecinConfiguration()
//            : this("dbo")
//        {
//        }

//        public MedecinConfiguration(string schema)
//        {
//            ToTable("Medecins", schema);
//            HasKey(x => x.Id);

//            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
//            Property(x => x.Nom).HasColumnName(@"Nom").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.Tel).HasColumnName(@"Tel").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.Adresse).HasColumnName(@"Adresse").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.Type).HasColumnName(@"Type").HasColumnType("int").IsRequired();
//            Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").HasColumnType("datetime").IsOptional();
//            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.ModifiedAt).HasColumnName(@"ModifiedAt").HasColumnType("datetime").IsOptional();
//        }
//    }

//    // Medicaments
//    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
//    public class MedicamentConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Medicament>
//    {
//        public MedicamentConfiguration()
//            : this("dbo")
//        {
//        }

//        public MedicamentConfiguration(string schema)
//        {
//            ToTable("Medicaments", schema);
//            HasKey(x => x.Id);

//            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
//            Property(x => x.CnasId).HasColumnName(@"CnasId").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.Nom).HasColumnName(@"Nom").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.Dci).HasColumnName(@"Dci").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.Dose).HasColumnName(@"Dose").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.Boite).HasColumnName(@"Boite").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.Tr).HasColumnName(@"Tr").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.Unite).HasColumnName(@"Unite").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.Remboursable).HasColumnName(@"Remboursable").HasColumnType("bit").IsRequired();
//            Property(x => x.Controle).HasColumnName(@"Controle").HasColumnType("bit").IsRequired();
//            Property(x => x.FormeId).HasColumnName(@"FormeId").HasColumnType("int").IsOptional();
//            Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").HasColumnType("datetime").IsOptional();
//            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.ModifiedAt).HasColumnName(@"ModifiedAt").HasColumnType("datetime").IsOptional();

//            // Foreign keys
//            HasOptional(a => a.Forme).WithMany(b => b.Medicaments).HasForeignKey(c => c.FormeId).WillCascadeOnDelete(false); // FK_dbo.Medicaments_dbo.Formes_FormeId
//        }
//    }

//    // MedOrds
//    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
//    public class MedOrdConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<MedOrd>
//    {
//        public MedOrdConfiguration()
//            : this("dbo")
//        {
//        }

//        public MedOrdConfiguration(string schema)
//        {
//            ToTable("MedOrds", schema);
//            HasKey(x => x.Id);

//            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
//            Property(x => x.OrdonnanceId).HasColumnName(@"OrdonnanceId").HasColumnType("int").IsRequired();
//            Property(x => x.MedicamentId).HasColumnName(@"MedicamentId").HasColumnType("int").IsRequired();
//            Property(x => x.Duree).HasColumnName(@"Duree").HasColumnType("int").IsRequired();
//            Property(x => x.Quantite).HasColumnName(@"Quantite").HasColumnType("int").IsRequired();
//            Property(x => x.Ppa).HasColumnName(@"Ppa").HasColumnType("float").IsRequired();
//            Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").HasColumnType("datetime").IsOptional();
//            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.ModifiedAt).HasColumnName(@"ModifiedAt").HasColumnType("datetime").IsOptional();

//            // Foreign keys
//            HasRequired(a => a.Medicament).WithMany(b => b.MedOrds).HasForeignKey(c => c.MedicamentId); // FK_dbo.MedOrds_dbo.Medicaments_MedicamentId
//            HasRequired(a => a.Ordonnance).WithMany(b => b.MedOrds).HasForeignKey(c => c.OrdonnanceId); // FK_dbo.MedOrds_dbo.Ordonnances_OrdonnanceId
//        }
//    }

//    // Operations
//    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
//    public class OperationConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Operation>
//    {
//        public OperationConfiguration()
//            : this("dbo")
//        {
//        }

//        public OperationConfiguration(string schema)
//        {
//            ToTable("Operations", schema);
//            HasKey(x => x.Id);

//            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
//            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").HasColumnType("datetime").IsOptional();
//            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.ModifiedAt).HasColumnName(@"ModifiedAt").HasColumnType("datetime").IsOptional();
//        }
//    }

//    // Ordonnances
//    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
//    public class OrdonnanceConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Ordonnance>
//    {
//        public OrdonnanceConfiguration()
//            : this("dbo")
//        {
//        }

//        public OrdonnanceConfiguration(string schema)
//        {
//            ToTable("Ordonnances", schema);
//            HasKey(x => x.Id);

//            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
//            Property(x => x.ServiDate).HasColumnName(@"ServiDate").HasColumnType("datetime").IsRequired();
//            Property(x => x.SoineDate).HasColumnName(@"SoineDate").HasColumnType("datetime").IsRequired();
//            Property(x => x.MedecinId).HasColumnName(@"MedecinId").HasColumnType("int").IsOptional();
//            Property(x => x.PatientId).HasColumnName(@"PatientId").HasColumnType("int").IsRequired();
//            Property(x => x.FactureId).HasColumnName(@"FactureId").HasColumnType("int").IsOptional();
//            Property(x => x.IsChronique).HasColumnName(@"IsChronique").HasColumnType("bit").IsRequired();
//            Property(x => x.IsHorsRegion).HasColumnName(@"IsHorsRegion").HasColumnType("bit").IsRequired();
//            Property(x => x.PathologieCode).HasColumnName(@"PathologieCode").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").HasColumnType("datetime").IsOptional();
//            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.ModifiedAt).HasColumnName(@"ModifiedAt").HasColumnType("datetime").IsOptional();
//            Property(x => x.PathologieId).HasColumnName(@"Pathologie_Id").HasColumnType("int").IsOptional();

//            // Foreign keys
//            HasOptional(a => a.Facture).WithMany(b => b.Ordonnances).HasForeignKey(c => c.FactureId).WillCascadeOnDelete(false); // FK_dbo.Ordonnances_dbo.Factures_FactureId
//            HasOptional(a => a.Medecin).WithMany(b => b.Ordonnances).HasForeignKey(c => c.MedecinId).WillCascadeOnDelete(false); // FK_dbo.Ordonnances_dbo.Medecins_MedecinId
//            HasOptional(a => a.Pathology).WithMany(b => b.Ordonnances).HasForeignKey(c => c.PathologieId).WillCascadeOnDelete(false); // FK_dbo.Ordonnances_dbo.Pathologies_Pathologie_Id
//            HasRequired(a => a.Patient).WithMany(b => b.Ordonnances).HasForeignKey(c => c.PatientId); // FK_dbo.Ordonnances_dbo.Patients_PatientId
//        }
//    }

//    // Pathologies
//    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
//    public class PathologyConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Pathology>
//    {
//        public PathologyConfiguration()
//            : this("dbo")
//        {
//        }

//        public PathologyConfiguration(string schema)
//        {
//            ToTable("Pathologies", schema);
//            HasKey(x => x.Id);

//            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
//            Property(x => x.Code).HasColumnName(@"Code").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.Nom).HasColumnName(@"Nom").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").HasColumnType("datetime").IsOptional();
//            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.ModifiedAt).HasColumnName(@"ModifiedAt").HasColumnType("datetime").IsOptional();
//        }
//    }

//    // Patients
//    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
//    public class PatientConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Patient>
//    {
//        public PatientConfiguration()
//            : this("dbo")
//        {
//        }

//        public PatientConfiguration(string schema)
//        {
//            ToTable("Patients", schema);
//            HasKey(x => x.Id);

//            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
//            Property(x => x.Nom).HasColumnName(@"Nom").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.Prenom).HasColumnName(@"Prenom").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.DateNaissance).HasColumnName(@"DateNaissance").HasColumnType("datetime").IsOptional();
//            Property(x => x.Alliance).HasColumnName(@"Alliance").HasColumnType("int").IsRequired();
//            Property(x => x.Du).HasColumnName(@"Du").HasColumnType("datetime").IsOptional();
//            Property(x => x.Au).HasColumnName(@"Au").HasColumnType("datetime").IsOptional();
//            Property(x => x.AssureId).HasColumnName(@"AssureId").HasColumnType("int").IsRequired();
//            Property(x => x.Suspende).HasColumnName(@"Suspende").HasColumnType("bit").IsRequired();
//            Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").HasColumnType("datetime").IsOptional();
//            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.ModifiedAt).HasColumnName(@"ModifiedAt").HasColumnType("datetime").IsOptional();

//            // Foreign keys
//            HasRequired(a => a.Assure).WithMany(b => b.Patients).HasForeignKey(c => c.AssureId); // FK_dbo.Patients_dbo.Assures_AssureId
//        }
//    }

//    // Users
//    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
//    public class UserConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<User>
//    {
//        public UserConfiguration()
//            : this("dbo")
//        {
//        }

//        public UserConfiguration(string schema)
//        {
//            ToTable("Users", schema);
//            HasKey(x => x.Id);

//            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
//            Property(x => x.UserName).HasColumnName(@"UserName").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.Password).HasColumnName(@"Password").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.FullName).HasColumnName(@"FullName").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.IsAdmin).HasColumnName(@"IsAdmin").HasColumnType("bit").IsRequired();
//            Property(x => x.IsWork).HasColumnName(@"IsWork").HasColumnType("bit").IsRequired();
//            Property(x => x.AllowAdd).HasColumnName(@"AllowAdd").HasColumnType("bit").IsRequired();
//            Property(x => x.AllowUpdate).HasColumnName(@"AllowUpdate").HasColumnType("bit").IsRequired();
//            Property(x => x.AllowPrintDocs).HasColumnName(@"AllowPrintDocs").HasColumnType("bit").IsRequired();
//            Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").HasColumnType("datetime").IsOptional();
//            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("nvarchar(max)").IsOptional();
//            Property(x => x.ModifiedAt).HasColumnName(@"ModifiedAt").HasColumnType("datetime").IsOptional();
//        }
//    }

//    #endregion

//}
//// </auto-generated>

